float:
  any:
  - base_args: ['@metric']
    constructor: PGVector_MultiProccess
    disabled: false
    docker_tag: ann-benchmarks-pgvector_multiprocess
    module: ann_benchmarks.algorithms.pgvector_multiprocess
    name: pgvector_multiprocess
    run_groups:
      M-16:
        arg_groups: [{M: 16, efConstruction: 200, efSearch: 150}]
        args: {}
        query_args: [[1, 5, 10, 20, 30, 50]]
